import { Jobs } from './models/jobs.model';

export const jobsMock: Jobs[] = [
  {
    id: 1,
    company: 'Tech Innovations',
    expires: '2024-09-30',
    position: 'Software Engineer',
    startingSalary: 70000,
    workType: 'remote',
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: '3+ years of experience in JavaScript and TypeScript',
    description:
      'Join our dynamic team to work on cutting-edge software solutions.',
    isApplied: false,
  },
  {
    id: 2,
    company: 'Creative Labs',
    expires: '2024-10-15',
    position: 'UX Designer',
    startingSalary: 65000,
    workType: 'hybrid',
    location: 'New York, NY',
    country: 'USA',
    qualifications: 'Experience with Adobe Creative Suite and user research',
    description:
      'Create engaging user experiences for our web and mobile applications.',
    isApplied: true,
  },
  {
    id: 3,
    company: 'GreenTech',
    expires: '2024-08-31',
    position: 'Environmental Scientist',
    startingSalary: 80000,
    workType: 'onsite',
    location: 'Denver, CO',
    country: 'USA',
    qualifications: 'Degree in Environmental Science or related field',
    description:
      'Conduct research and provide solutions to environmental issues.',
    isApplied: false,
  },
  {
    id: 4,
    company: 'DataWorld',
    expires: '2024-11-01',
    position: 'Data Analyst',
    startingSalary: 72000,
    workType: 'remote',
    location: 'Austin, TX',
    country: 'USA',
    qualifications: 'Proficiency in SQL and data visualization tools',
    description: 'Analyze complex data sets to provide actionable insights.',
    isApplied: false,
  },
  {
    id: 5,
    company: 'MedTech',
    expires: '2024-09-10',
    position: 'Biomedical Engineer',
    startingSalary: 75000,
    workType: 'onsite',
    location: 'Boston, MA',
    country: 'USA',
    qualifications: 'Experience with medical device design',
    description: 'Develop and improve medical devices and technologies.',
    isApplied: true,
  },
];
